uhafner/autograding-model

pom.xml
src/main/java/edu/hm/hafner/grading/AggregatedScore.java
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/PitMarkdown.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java
src/test/java/edu/hm/hafner/grading/PitMarkdownTest.java
src/test/java/edu/hm/hafner/grading/ScoreTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

Move Markdown generation of https://github.com/uhafner/autograding-github-action to model.

Move Markdown generation to model

---

src/main/java/edu/hm/hafner/grading/PitMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

- Use correct :microbe: icon for PIT reports
- Add a column for the name of the test results to table

Fix report bugs

---

.github/workflows/autograding.yml
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/GradingReport.java
src/main/java/edu/hm/hafner/grading/PitMarkdown.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/java/edu/hm/hafner/grading/PitMarkdownTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

Add impact row and simplify row creation

---

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/PitMarkdown.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

Example result:
|Name|Passed|Skipped|Failed|Impact
|:-:|:-:|:-:|:-:|:-:
|First|3|2|1|-7
|Second|1|2|3|-17
|**Total**|**4**|**4**|**4**|**-24**
|*Impact*|*0*|*-1*|*-5*|*-*

Add a summary row to the table (tests and analysis)

---

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/GradingReport.java
src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

Example:
14 tests failed, 5 passed, 3 skipped
70% Covered , 30% Missed 
60% Killed , 40% Survived 
10 warnings found (1 errors, 2 high, 3 normal, 4 low)
10 warnings found (4 errors, 3 high, 2 normal, 1 low)

Add a summary, that can be used as a comment in a PR

---

.github/workflows/autograding.yml
.github/workflows/reporting.yml
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/Configuration.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageScore.java
src/main/java/edu/hm/hafner/grading/GradingReport.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java

In some assignments, we start with zero code.  That means the model does not contain coverage information yet. Here we should assume a coverage of 0.

Do not throw an exception if the coverage is missing

---

src/main/java/edu/hm/hafner/grading/AggregatedScore.java
src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java
src/test/resources/edu/hm/hafner/grading/mutations.xml

All coverage scores need to be considered to obtain the file nodes.

Add missing mutation file nodes

---

doc/dependency-graph.puml
src/main/java/edu/hm/hafner/grading/CommentBuilder.java
src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java

It makes sense to style different comment types differently.

Add the type of comment (warning, coverage, mutation)

---

doc/dependency-graph.puml
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/main/java/edu/hm/hafner/grading/TruncatedString.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
src/test/java/edu/hm/hafner/grading/TruncatedStringTest.java

GitHub has a limit of 65536 characters, GitLab 1000000.

Truncate output of details markdown

---

src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java

So we can use the same model for different things.

Make the display name overridable

---

src/main/java/edu/hm/hafner/grading/GradingReport.java

Otherwise the header is not shown correctly.

Add a newline before the markdown section

---

src/main/resources/default-config.json
src/main/resources/default-no-score-config.json

Followup to https://github.com/uhafner/codingstyle-pom/releases/tag/v4.0.0

Improve glob to pick up multiple PMD and CheckStyle files

---

src/main/java/edu/hm/hafner/grading/CommentBuilder.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CommentBuilderTest.java

It makes sense to show only a couple of line comments.

Make the number of line comments configurable

---

src/main/java/edu/hm/hafner/grading/AggregatedScore.java
src/main/java/edu/hm/hafner/grading/CoverageScore.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java

Improve logging so that the sub scores are shown as well as the aggregation.

Add logging for sub scores

---

pom.xml

See https://github.com/jenkinsci/analysis-model/releases/tag/v12.3.1

Fix PMD logo path

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/coverage.yml
.github/workflows/quality-monitor.yml
.github/workflows/update-badges.yml
pom.xml
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/AnalysisScore.java
src/main/java/edu/hm/hafner/grading/FileSystemAnalysisReportFactory.java
src/main/java/edu/hm/hafner/grading/ReportFinder.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/FileSystemAnalysisReportFactoryTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/resources/edu/hm/hafner/grading/error-prone.log

- Simplify warnings message.
- Use the configured icon if set.

Improve layout of Markdown

---

src/main/java/edu/hm/hafner/grading/AnalysisScore.java
src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageScore.java
src/main/java/edu/hm/hafner/grading/GradingReport.java
src/main/java/edu/hm/hafner/grading/MetricScore.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestScore.java
src/main/resources/default-config.json
src/main/resources/default-no-score-config.json
src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java

Add correct default configuration and fix newlines.

Fix broken default configuration

---

src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/test/java/edu/hm/hafner/grading/MetricMarkdownTest.java

Using an icon in the header and in the items does not look good...

Add new text title method without an icon

---

pom.xml
src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java
src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/MetricMarkdown.java
src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java
src/main/java/edu/hm/hafner/grading/Score.java
src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java
src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java
src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java
src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java
src/test/java/edu/hm/hafner/grading/GradingReportTest.java
src/test/java/edu/hm/hafner/grading/ReportFinderTest.java
src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
src/test/resources/edu/hm/hafner/grading/test-results/TEST-edu.hm.hafner.java2.assignment1.ArchitectureTest.xml
src/test/resources/edu/hm/hafner/grading/test-results/TEST-edu.hm.hafner.java2.assignment1.AssignmentTest.xml
src/test/resources/edu/hm/hafner/grading/test-results/TEST-edu.hm.hafner.java2.assignment1.ExamTest.xml

Tables and analysis results did not print all table columns. Additionally, the test table has been streamlined to show an icon as well.

Fix display of broken table columns

---

src/test/java/edu/hm/hafner/grading/CommentBuilderTest.java

Otherwise, publishing to Maven central will not work.
See https://github.com/uhafner/codingstyle-pom/pull/1303

Use the latest version of codingstyle-pom

---

pom.xml
src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java
src/main/java/edu/hm/hafner/grading/GradingReport.java
src/main/java/edu/hm/hafner/grading/QualityGate.java
src/main/java/edu/hm/hafner/grading/QualityGateEvaluation.java
src/main/java/edu/hm/hafner/grading/QualityGateResult.java
src/main/java/edu/hm/hafner/grading/QualityGatesConfiguration.java
src/main/java/edu/hm/hafner/grading/TestMarkdown.java
src/test/java/edu/hm/hafner/grading/QualityGateEvaluationTest.java
src/test/java/edu/hm/hafner/grading/QualityGateResultTest.java
src/test/java/edu/hm/hafner/grading/QualityGateTest.java
src/test/java/edu/hm/hafner/grading/QualityGatesConfigurationTest.java

Simplify processing of quality gates so it is simpler to use them in all the downstream projects. Fix quality gates for warnings.

Improve handling of quality gates

---

src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java

In GitLab there is no status to show that the action failed. There we need to fail the whole action.

Improve handling of failed quality gates
