pom.xml, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java
Since GitHub shows at least 65535 characters in the checks text we need to skip test failures.
=>  Truncate test failures if too large

src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CommentBuilder.java, src/main/java/edu/hm/hafner/grading/Configuration.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java
Comments for static analysis warnings, for lines with missing coverage, and for lines with survived mutations can be rendered in GitHub and GitLab using different APIs. The base class that creates the comments is now part of the model while the implementations that use the vendor specific API are placed in the corresponding actions.
=> Move comments creation to the model

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
- :vertical_traffic_light: JUnit - 77 of 100: 14 tests failed, 5 passed, 3 skipped
- :footprints: JaCoCo - 40 of 100: 70% coverage achieved
- :microscope: PIT - 20 of 100: 60% mutations killed
- :warning: Style - 30 of 100: 10 warnings found (1 error, 2 high, 3 normal, 4 low)
- :bug: Bugs - 0 of 100: 10 warnings found (4 errors, 3 high, 2 normal, 1 low)
|Name|Passed|Skipped|Failed|Total|Impact
|:-:|:-:|:-:|:-:|:-:|:-:
|Integrationstests|5|3|4|12|27
|Modultests|0|0|10|10|-50
|**Total**|**5**|**3**|**14**|**22**|**-23**
|:moneybag:|*10*|*-1*|*-5*|:heavy_minus_sign:|:heavy_minus_sign:
- test-class-skipped-0#test-skipped-0
- test-class-skipped-1#test-skipped-1
- test-class-skipped-2#test-skipped-2
__test-class-failed-0:test-failed-0__
failed-message-0
<details>
<summary>Stack Trace</summary> …
=> Improve markdown content

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageConfiguration.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/Score.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/main/java/edu/hm/hafner/grading/TruncatedString.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
The autograding model can be now used out-of-the-box to get a detailed report of the quality of a software project. If there are no scores set, then the scoring details will be omitted. 
- :vertical_traffic_light: JUnit: 14 tests failed, 5 passed, 3 skipped
- :footprints: JaCoCo: 70% coverage achieved
- :microscope: PIT: 60% mutations killed
- :warning: Style: 10 warnings found (1 error, 2 high, 3 normal, 4 low)
- :bug: Bugs: 10 warnings found (4 errors, 3 high, 2 normal, 1 low)
|Name|Passed|Skipped|Failed|Total
|:-:|:-:|:-:|:-:|:-:
|Integrationstests|5|3|4|12
|Modultests|0|0|10|10
|**Total**|**5**|**3**|**14**|**22**
- test-class-skipped-0#test-skipped-0
- test-class-skipped-1#test-skipped-1
- test-class-skipped-2#test-skipped-2
__test-class-failed-0:test-failed-0__
failed-message-0 …
=> Add support for configurations without score

.github/workflows/autograding.yml, .github/workflows/pr-quality-check.yml, src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/Score.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/resources/default-no-score-config.json, src/test/java/edu/hm/hafner/grading/GradingReportTest.java
New:
align="left" alt="Score percentage: 33%"
src="https://raw.githubusercontent.com/uhafner/autograding-model/main/percentages/033.svg" />
- :vertical_traffic_light: JUnit - 77 of 100: 14 tests failed, 5 passed, 3 skipped
- :footprints: JaCoCo - 40 of 100: 70% coverage achieved
- :microscope: PIT - 20 of 100: 60% mutations killed
- :warning: Style - 30 of 100: 10 warnings found (1 error, 2 high, 3 normal, 4 low)
- :bug: Bugs - 0 of 100: 10 warnings found (4 errors, 3 high, 2 normal, 1 low)
=> Show percentages as an image

src/main/java/edu/hm/hafner/grading/FileSystemCoverageReportFactory.java
Sometimes there might be no tests in a test class yet.
=> Ignore errors while parsing test files

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/JacksonFacade.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java, src/test/java/edu/hm/hafner/grading/TestScoreTest.java
When there are multiple analysis or testing configurations, then the total of each configuration should be computed of the containing sub-scores and not of the overall aggregation.
=> Fix total computation of scores

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/FileSystemAnalysisReportFactory.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AnalysisScoreTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
With https://github.com/uhafner/codingstyle-pom/releases/tag/v4.0.0 a project has multiple reports for CheckStyle and PMD by default. It makes sense to show the number of processed reports as well.
=> Add number of processed files to report

src/main/java/edu/hm/hafner/grading/CommentBuilder.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java
For analysis issues, these details will be filled with the documentation of the corresponding static analysis tool.
Required for https://github.com/uhafner/autograding-gitlab-action/issues/27
=> Add markdown details as additional parameter to create source code annotations

pom.xml, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java
Also show the version in the autograding log.
=> Add methods to read Maven version and Git hash

pom.xml, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
=> Improve overview of summary for quality monitor (without grading values)

pom.xml, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java
Will fix https://github.com/uhafner/quality-monitor/issues/39
=> Add a newline before the error message Markdown.

.mvn/maven.config, src/main/java/edu/hm/hafner/grading/AnalysisConfiguration.java, src/main/java/edu/hm/hafner/grading/CommentBuilder.java, src/test/java/edu/hm/hafner/grading/AnalysisScoreTest.java, src/test/java/edu/hm/hafner/grading/CommentBuilderTest.java
When students create a lot of issues, it makes sense to hide the descriptions.
=> Add a flag to hide the descriptions

src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java
Newlines should be marked with a backslash to conform to the Markdown specification. Otherwise they are not correctly shown in GitLab.
=> Fix new lines in summary

src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/FileSystemCoverageReportFactory.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TruncatedString.java, src/test/java/edu/hm/hafner/grading/TruncatedStringTest.java
GitHub and GitLab handle newlines in Markdown differently. All elements are now correctly provided as standalone blocks that can be concatenated on demand.
Will fix #381.
=> Fix handling of newlines and paragraphs

.github/workflows/quality-monitor.yml, pom.xml, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AnalysisScoreTest.java, src/test/java/edu/hm/hafner/grading/FileSystemAnalysisReportFactoryTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java
Uses the following type mapping:
- WARNING -> "warning";
- BUG -> "bug";
- DUPLICATION -> "duplication";
- VULNERABILITY -> "vulnerability";
=> Use specific parser type names

.github/workflows/quality-monitor.yml, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
Showing disabled scores is good for debugging but not for the actual evaluation of projects, so it makes sense to hide these elements.
Additionally, line breaks in unit tests and summaries were still broken and should be fixed now.
=> Improve rendering of details and summary

.github/workflows/quality-monitor.yml, .github/workflows/update-badges.yml, pom.xml, src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/FileSystemCoverageReportFactory.java, src/main/java/edu/hm/hafner/grading/FileSystemMetricReportFactory.java, src/main/java/edu/hm/hafner/grading/FileSystemTestReportFactory.java, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/MetricConfiguration.java, src/main/java/edu/hm/hafner/grading/MetricMarkdown.java, src/main/java/edu/hm/hafner/grading/MetricScore.java, src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java, src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/MetricMarkdownTest.java, src/test/java/edu/hm/hafner/grading/ReportFinderTest.java, src/test/resources/edu/hm/hafner/grading/metrics.xml
The latest release of the coverage-model supports reporting of software metrics. While it does not yet make sense to use them in autograding, it would be helpful to show the results of the recorded metrics in the quality monitor.
=> Add support for software metrics

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/CodeCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/FileSystemMetricReportFactory.java, src/main/java/edu/hm/hafner/grading/FileSystemTestReportFactory.java, src/main/java/edu/hm/hafner/grading/MetricMarkdown.java, src/main/java/edu/hm/hafner/grading/MetricScore.java, src/main/java/edu/hm/hafner/grading/MutationCoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/Score.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/main/java/edu/hm/hafner/grading/ToolConfiguration.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageConfigurationTest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/FileSystemCoverageReportFactoryTest.java, src/test/java/edu/hm/hafner/grading/FileSystemTestReportFactoryTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/MetricMarkdownTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
Refactor icon handling:
1. check the icon of the tool
2. check the specific icon in the registry
3. check the icon of the configuration
4. dallback: default icon of markdown class
=> Add icon parameter for tools.

src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/Score.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java, src/test/java/edu/hm/hafner/grading/TestScoreTest.java
When `maxScore=50` then the impact of 50% success should be 25.
=> Scale scores that are based on percentages by maxScore

pom.xml, src/main/java/edu/hm/hafner/grading/GradingReport.java, src/main/java/edu/hm/hafner/grading/MetricMarkdown.java, src/main/java/edu/hm/hafner/grading/MetricScore.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/test/java/edu/hm/hafner/grading/AnalysisMarkdownTest.java, src/test/java/edu/hm/hafner/grading/CoverageMarkdownTest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/MetricMarkdownTest.java, src/test/java/edu/hm/hafner/grading/ReportFinderTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
See coverage-model for details.
=> Use new rendering methods of coverage model

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/FileSystemToolParser.java, src/test/java/edu/hm/hafner/grading/ReportFinderTest.java
When a configuration instance does not define a name, then the metric should be used.
=> Add fallback name if no configuration name is specified

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/FileSystemToolParser.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/ReportFinderTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
Even if the rounded value is 100%, we should only report a 99% success rate when a test is failing.
Fixes #407
=> If there are failed tests then show 99% success only

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/AnalysisScore.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/main/java/edu/hm/hafner/grading/FileSystemToolParser.java, src/main/java/edu/hm/hafner/grading/MetricScore.java, src/main/java/edu/hm/hafner/grading/Score.java, src/main/java/edu/hm/hafner/grading/ScoreBuilder.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/AnalysisScoreTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java, src/test/java/edu/hm/hafner/grading/TestScoreTest.java
It makes sense to define a default name for each of the scores. If no name is given, this default name will be picked.
=> Fix default names of scores

src/main/java/edu/hm/hafner/grading/TestConfiguration.java, src/test/java/edu/hm/hafner/grading/TestScoreTest.java
When tests use a negative relative impact then we need to start counting from 100 minus the impact.
=> Fix test score computation for negative impact

pom.xml, src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java, src/main/java/edu/hm/hafner/grading/CoverageScore.java, src/test/java/edu/hm/hafner/grading/CoverageScoreTest.java
E.g., assignments without branches should not have a negative impact on the overall coverage score.
=> Set the impact to zero if the coverage is not set

src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
The Markdown renderer of GitHub seems to have a bug when an icon is shown with emojis on the same line.
=> Remove emojis in the summary message of tests

pom.xml, src/main/java/edu/hm/hafner/grading/AnalysisMarkdown.java, src/main/java/edu/hm/hafner/grading/CoverageMarkdown.java, src/main/java/edu/hm/hafner/grading/MetricMarkdown.java, src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
Before this change, the entire test output was truncated. As a result, important subsequent test results were hidden. Now the test output is created step by step and each step will be truncated separately.
Fixes uhafner/autograding-gitlab-action#119
=> Truncate the test output separately for each block

src/main/java/edu/hm/hafner/grading/AutoGradingRunner.java
So all actions automatically participate in quality gates. If required, a runner subclass can handle failed quality gates.
=> Move quality gate evaluation into auto grading runner

src/main/java/edu/hm/hafner/grading/AggregatedScore.java, src/main/java/edu/hm/hafner/grading/QualityGate.java, src/main/java/edu/hm/hafner/grading/QualityGatesConfiguration.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/AggregatedScoreTest.java, src/test/java/edu/hm/hafner/grading/AutoGradingRunnerITest.java, src/test/java/edu/hm/hafner/grading/GradingReportTest.java, src/test/java/edu/hm/hafner/grading/QualityGateEvaluationTest.java, src/test/java/edu/hm/hafner/grading/QualityGateTest.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java, src/test/java/edu/hm/hafner/grading/TestScoreTest.java
Do not include skipped tests in success rate. This fixes #465.
Additionally, add the new metrics `tests-success-rate` and `tests-failure-rate` to the metrics summary. These metrics are required to create quality gates for tests.
Also make sure that unknown metrics do not fail the build as static analysis warnings may use an aggregation.
=> Improve handling of test metrics

src/main/java/edu/hm/hafner/grading/ScoreMarkdown.java, src/main/java/edu/hm/hafner/grading/TestMarkdown.java, src/main/java/edu/hm/hafner/grading/TestScore.java, src/test/java/edu/hm/hafner/grading/TestMarkdownTest.java
Added a summary icon column for the overall test results.
I named the column “Complete” because I thought it would be more appropriate for ✅ and ❌.
Will fix #503
=> Add status icon column for test results
